-- ================================================================
-- DJ PIXULA SPOTIFY STATS
-- SUPABASE: TABLA NORMALIZADA + VISTAS DE ESTADÍSTICAS
-- ================================================================
-- IMPORTANTE:
-- Este script NO guarda IP, user agent, país, plataforma ni otros
-- datos técnicos del export de Spotify. Solo conserva lo necesario
-- para el perfil estadístico.
-- ================================================================

-- ----------------------------------------------------------------
-- 1. TABLA PRINCIPAL
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.spotify_history_extended (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key TEXT NOT NULL UNIQUE,
    played_at TIMESTAMPTZ NOT NULL,
    track_name TEXT NOT NULL,
    artist_name TEXT NOT NULL,
    album_name TEXT,
    album_cover TEXT,
    spotify_track_uri TEXT,
    spotify_album_uri TEXT,
    ms_played BIGINT NOT NULL DEFAULT 0,
    skipped BOOLEAN NOT NULL DEFAULT FALSE,
    shuffle BOOLEAN NOT NULL DEFAULT FALSE,
    offline BOOLEAN NOT NULL DEFAULT FALSE,
    incognito_mode BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Si la tabla ya existía y faltaban columnas, las agrega sin borrar datos.
ALTER TABLE public.spotify_history_extended
    ADD COLUMN IF NOT EXISTS spotify_album_uri TEXT;

ALTER TABLE public.spotify_history_extended
    ADD COLUMN IF NOT EXISTS album_cover TEXT;

ALTER TABLE public.spotify_history_extended
    ADD COLUMN IF NOT EXISTS ms_played BIGINT NOT NULL DEFAULT 0;

ALTER TABLE public.spotify_history_extended
    ADD COLUMN IF NOT EXISTS skipped BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE public.spotify_history_extended
    ADD COLUMN IF NOT EXISTS shuffle BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE public.spotify_history_extended
    ADD COLUMN IF NOT EXISTS offline BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE public.spotify_history_extended
    ADD COLUMN IF NOT EXISTS incognito_mode BOOLEAN NOT NULL DEFAULT FALSE;

-- ----------------------------------------------------------------
-- 2. ÍNDICES
-- ----------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_spotify_history_extended_played_at
    ON public.spotify_history_extended (played_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_spotify_history_extended_track_uri
    ON public.spotify_history_extended (spotify_track_uri);

CREATE INDEX IF NOT EXISTS idx_spotify_history_extended_recent
    ON public.spotify_history_extended (played_at DESC)
    WHERE ms_played > 0;

-- ----------------------------------------------------------------
-- 3. RLS
-- La web pública solo necesita LEER las estadísticas/historial.
-- La importación usa una secret/service_role key desde Node.js.
-- ----------------------------------------------------------------
ALTER TABLE public.spotify_history_extended ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read spotify history" ON public.spotify_history_extended;

CREATE POLICY "Public read spotify history"
ON public.spotify_history_extended
FOR SELECT
TO anon, authenticated
USING (TRUE);

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT ON TABLE public.spotify_history_extended TO anon, authenticated;

-- No se concede INSERT/UPDATE/DELETE a anon ni authenticated.

-- ----------------------------------------------------------------
-- 4. TOP 10 CANCIONES - ÚLTIMOS 90 DÍAS
-- Cada fila del historial con ms_played > 0 cuenta como una reproducción.
-- Los skips NO se eliminan: si el evento está registrado como escucha,
-- sigue formando parte del historial.
-- ----------------------------------------------------------------
CREATE OR REPLACE VIEW public.view_top_tracks_recent
WITH (security_invoker = true)
AS
SELECT
    track_name,
    artist_name,
    MAX(album_cover) FILTER (
        WHERE album_cover IS NOT NULL AND BTRIM(album_cover) <> ''
    ) AS album_cover,
    MAX(spotify_track_uri) FILTER (
        WHERE spotify_track_uri IS NOT NULL AND BTRIM(spotify_track_uri) <> ''
    ) AS spotify_track_uri,
    COUNT(*)::INT AS veces_reproducidas
FROM public.spotify_history_extended
WHERE played_at >= CURRENT_TIMESTAMP - INTERVAL '90 days'
  AND ms_played > 0
  AND BTRIM(track_name) <> ''
GROUP BY track_name, artist_name
ORDER BY veces_reproducidas DESC, track_name ASC, artist_name ASC
LIMIT 10;

-- ----------------------------------------------------------------
-- 5. TOP 5 ÁLBUMES - ÚLTIMOS 90 DÍAS
-- Suma las reproducciones de TODAS las canciones del álbum.
-- ----------------------------------------------------------------
CREATE OR REPLACE VIEW public.view_top_albums_recent
WITH (security_invoker = true)
AS
SELECT
    COALESCE(NULLIF(BTRIM(album_name), ''), 'Álbum desconocido') AS album_name,
    artist_name,
    MAX(album_cover) FILTER (
        WHERE album_cover IS NOT NULL AND BTRIM(album_cover) <> ''
    ) AS album_cover,
    MAX(spotify_album_uri) FILTER (
        WHERE spotify_album_uri IS NOT NULL AND BTRIM(spotify_album_uri) <> ''
    ) AS spotify_album_uri,
    COUNT(*)::INT AS veces_reproducidas
FROM public.spotify_history_extended
WHERE played_at >= CURRENT_TIMESTAMP - INTERVAL '90 days'
  AND ms_played > 0
  AND BTRIM(track_name) <> ''
  AND BTRIM(COALESCE(album_name, '')) <> ''
GROUP BY
    COALESCE(NULLIF(BTRIM(album_name), ''), 'Álbum desconocido'),
    artist_name
ORDER BY veces_reproducidas DESC, album_name ASC, artist_name ASC
LIMIT 5;

-- ----------------------------------------------------------------
-- 6. TOP 10 CANCIONES - TODOS LOS TIEMPOS
-- ----------------------------------------------------------------
CREATE OR REPLACE VIEW public.view_top_tracks_all_time
WITH (security_invoker = true)
AS
SELECT
    track_name,
    artist_name,
    MAX(album_cover) FILTER (
        WHERE album_cover IS NOT NULL AND BTRIM(album_cover) <> ''
    ) AS album_cover,
    MAX(spotify_track_uri) FILTER (
        WHERE spotify_track_uri IS NOT NULL AND BTRIM(spotify_track_uri) <> ''
    ) AS spotify_track_uri,
    COUNT(*)::INT AS veces_reproducidas
FROM public.spotify_history_extended
WHERE ms_played > 0
  AND BTRIM(track_name) <> ''
GROUP BY track_name, artist_name
ORDER BY veces_reproducidas DESC, track_name ASC, artist_name ASC
LIMIT 10;

-- ----------------------------------------------------------------
-- 7. TOP 5 ÁLBUMES - TODOS LOS TIEMPOS
-- ----------------------------------------------------------------
CREATE OR REPLACE VIEW public.view_top_albums_all_time
WITH (security_invoker = true)
AS
SELECT
    COALESCE(NULLIF(BTRIM(album_name), ''), 'Álbum desconocido') AS album_name,
    artist_name,
    MAX(album_cover) FILTER (
        WHERE album_cover IS NOT NULL AND BTRIM(album_cover) <> ''
    ) AS album_cover,
    MAX(spotify_album_uri) FILTER (
        WHERE spotify_album_uri IS NOT NULL AND BTRIM(spotify_album_uri) <> ''
    ) AS spotify_album_uri,
    COUNT(*)::INT AS veces_reproducidas
FROM public.spotify_history_extended
WHERE ms_played > 0
  AND BTRIM(track_name) <> ''
  AND BTRIM(COALESCE(album_name, '')) <> ''
GROUP BY
    COALESCE(NULLIF(BTRIM(album_name), ''), 'Álbum desconocido'),
    artist_name
ORDER BY veces_reproducidas DESC, album_name ASC, artist_name ASC
LIMIT 5;

-- ----------------------------------------------------------------
-- 8. ÚLTIMAS 20 REPRODUCCIONES
-- El ID se conserva para desempatar registros con el mismo timestamp.
-- ----------------------------------------------------------------
CREATE OR REPLACE VIEW public.view_recent_plays
WITH (security_invoker = true)
AS
SELECT
    id,
    track_name,
    artist_name,
    album_name,
    album_cover,
    spotify_track_uri,
    played_at,
    ms_played
FROM public.spotify_history_extended
WHERE ms_played > 0
  AND BTRIM(track_name) <> ''
ORDER BY played_at DESC, id DESC
LIMIT 20;

-- ----------------------------------------------------------------
-- 9. PERMISOS DE LECTURA DE LAS VISTAS
-- ----------------------------------------------------------------
GRANT SELECT ON public.view_top_tracks_recent TO anon, authenticated;
GRANT SELECT ON public.view_top_albums_recent TO anon, authenticated;
GRANT SELECT ON public.view_top_tracks_all_time TO anon, authenticated;
GRANT SELECT ON public.view_top_albums_all_time TO anon, authenticated;
GRANT SELECT ON public.view_recent_plays TO anon, authenticated;

-- ----------------------------------------------------------------
-- 10. VERIFICACIÓN
-- ----------------------------------------------------------------
SELECT
    'spotify_history_extended' AS objeto,
    COUNT(*) AS registros
FROM public.spotify_history_extended

UNION ALL

SELECT 'view_top_tracks_recent', COUNT(*) FROM public.view_top_tracks_recent
UNION ALL
SELECT 'view_top_albums_recent', COUNT(*) FROM public.view_top_albums_recent
UNION ALL
SELECT 'view_top_tracks_all_time', COUNT(*) FROM public.view_top_tracks_all_time
UNION ALL
SELECT 'view_top_albums_all_time', COUNT(*) FROM public.view_top_albums_all_time
UNION ALL
SELECT 'view_recent_plays', COUNT(*) FROM public.view_recent_plays;
